const beaches=[
 {id:'haeundae',name:'해운대해수욕장',lat:35.158885,lon:129.161483,photo:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80',facility:'샤워·탈의실·산책로',food:'밀면',types:['밀면','돼지국밥','해산물']},
 {id:'gwangalli',name:'광안리해수욕장',lat:35.15089,lon:129.11908,photo:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=900&q=80',facility:'산책로·카페 거리',food:'조개구이',types:['조개구이','회','카페']},
 {id:'songjeong',name:'송정해수욕장',lat:35.179346,lon:129.200546,photo:'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80',facility:'서핑숍·샤워 시설',food:'물회',types:['물회','해산물','카페']},
 {id:'songdo',name:'송도해수욕장',lat:35.07564,lon:129.01881,photo:'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=900&q=80',facility:'산책로·케이블카 인근',food:'해산물',types:['해산물','조개구이','카페']},
 {id:'dadaepo',name:'다대포해수욕장',lat:35.047,lon:128.96323,photo:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',facility:'산책로·낙조분수 인근',food:'칼국수',types:['칼국수','해산물','분식']}
];
let current=beaches[0],purpose='산책',map,loaded=false;const weights={혼잡도:3,파도:3,날씨:4,주차:2,편의시설:3};const beachTraits={haeundae:{facility:95,fit:{물놀이:94,산책:78,서핑:45,'사진 촬영':86,'가족 여행':95,데이트:82,힐링:58}},gwangalli:{facility:88,fit:{물놀이:78,산책:90,서핑:48,'사진 촬영':96,'가족 여행':78,데이트:98,힐링:65}},songjeong:{facility:74,fit:{물놀이:82,산책:80,서핑:98,'사진 촬영':84,'가족 여행':72,데이트:72,힐링:88}},songdo:{facility:83,fit:{물놀이:68,산책:91,서핑:38,'사진 촬영':80,'가족 여행':88,데이트:80,힐링:76}},dadaepo:{facility:76,fit:{물놀이:80,산책:93,서핑:55,'사진 촬영':92,'가족 여행':86,데이트:75,힐링:96}}};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const weatherText=c=>c===0?['☀️','맑음']:c<=2?['🌤️','대체로 맑음']:c===3?['☁️','흐림']:c<=48?['🌫️','안개']:c<=67?['🌧️','비']:c<=77?['❄️','눈']:c<=82?['🌦️','소나기']:['⛈️','뇌우'];
const value=v=>v===null||v===undefined||Number.isNaN(Number(v))?null:Number(v);
function nowText(){return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())}
function congestion(b){const d=new Date(),h=+new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',hour:'numeric',hour12:false}).format(d),weekend=[0,6].includes(d.getDay());let score=(h>=11&&h<=17?3:1)+(weekend?2:0)+(b.id==='haeundae'||b.id==='gwangalli'?1:0);return score>=5?'혼잡':score>=3?'보통':'여유'}function parking(b){let c=congestion(b);return c==='혼잡'?'부족':c==='보통'?'보통':'여유'}
async function getJSON(url,label){console.info('[PadoPick API]',label,url);const r=await fetch(url);console.info('[PadoPick API response]',label,r.status);if(!r.ok)throw new Error(label+' HTTP '+r.status);return r.json()}
function nearest(hourly){if(!hourly?.time?.length)return null;const now=Date.now();let index=0,min=Infinity;hourly.time.forEach((t,i)=>{let d=Math.abs(new Date(t+'+09:00')-now);if(d<min){min=d;index=i}});return index}
async function fetchBeach(b){const q=`latitude=${b.lat}&longitude=${b.lon}&timezone=Asia%2FSeoul`;try{const w=await getJSON(`https://api.open-meteo.com/v1/forecast?${q}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,precipitation&hourly=precipitation_probability`,'weather');let i=nearest(w.hourly);b.weather={temp:w.current?.temperature_2m,feel:w.current?.apparent_temperature,code:w.current?.weather_code,wind:w.current?.wind_speed_10m,rain:w.current?.precipitation,prob:i===null?null:w.hourly.precipitation_probability?.[i],time:w.current?.time||null}}catch(e){console.error('[PadoPick API error] weather',b.name,e);b.weather=null}try{const m=await getJSON(`https://marine-api.open-meteo.com/v1/marine?${q}&current=wave_height,wave_direction,wave_period,sea_surface_temperature&hourly=wave_height,wave_direction,wave_period,sea_surface_temperature`,'marine');let i=nearest(m.hourly),c=m.current||{};b.marine={wave:value(c.wave_height,i===null?null:m.hourly.wave_height?.[i]),dir:value(c.wave_direction,i===null?null:m.hourly.wave_direction?.[i]),period:value(c.wave_period,i===null?null:m.hourly.wave_period?.[i]),sea:value(c.sea_surface_temperature,i===null?null:m.hourly.sea_surface_temperature?.[i]),time:c.time||null}}catch(e){console.error('[PadoPick API error] marine',b.name,e);b.marine=null}}
function score(b){if(!b.weather||!b.marine||!Number.isFinite(Number(b.marine.wave))||!Number.isFinite(Number(b.weather.code)))return null;let weather=Number(b.weather.code)<=3?100:Number(b.weather.code)<=67?60:25,wave=Number(b.marine.wave);let waveScore=purpose==='서핑'?Math.max(15,100-Math.abs(wave-1.1)*60):purpose==='물놀이'?Math.max(20,100-Math.max(0,wave-.6)*100):Math.max(30,100-wave*35);let crowd={여유:100,보통:65,혼잡:30}[congestion(b)],park={여유:100,보통:60,부족:25}[parking(b)],traits=beachTraits[b.id],purposeFit=traits?.fit?.[purpose];if(!Number.isFinite(purposeFit))return null;let priority=(weather*weights.날씨+waveScore*weights.파도+crowd*weights.혼잡도+park*weights.주차+traits.facility*weights.편의시설)/(weights.날씨+weights.파도+weights.혼잡도+weights.주차+weights.편의시설);let result=Math.round(priority*.82+purposeFit*.18);return Number.isFinite(result)?result:null}
function rank(b){let ordered=[...beaches].filter(x=>score(x)!==null).sort((a,c)=>score(c)-score(a));let n=ordered.findIndex(x=>x.id===b.id);return n<0?null:n+1}
function showClean(id){const b=beaches.find(x=>x.id===id),quality={haeundae:{score:5,cod:'0.3',coli:14},gwangalli:{score:8,cod:'1.0',coli:113},songjeong:{score:5,cod:'0.3',coli:203},songdo:{score:5,cod:'0.9',coli:428},dadaepo:{score:7,cod:'1.6',coli:120}}[id];let box=$('#cleanDetail');if(!box){box=document.createElement('section');box.id='cleanDetail';box.className='clean-detail';$('#cards').insertAdjacentElement('afterend',box)};$$('[data-clean]').forEach(x=>x.classList.toggle('selected',x.dataset.clean===id));box.innerHTML=`<p class="eyebrow">BUSAN OFFICIAL WATER QUALITY</p><h3>${b.name} 청결 정보</h3><p><b>수질등급: 적합</b> · 총점 ${quality.score}점</p><p>COD ${quality.cod} mg/L · 대장균군수 ${quality.coli} MPN/100mL</p><p>부산광역시 보건환경정보 공개시스템의 해수욕장 수질 공개 표 기준입니다. 해당 표의 채수일 표기는 5월 15일이며, 최신 측정은 아래 공식 자료에서 확인하세요.</p><p><a href="https://heis.busan.go.kr/environmental/water_04_002.aspx" target="_blank" rel="noopener">부산광역시 공식 수질 자료 보기 ↗</a></p>`;box.classList.add('visible')}
function card(b){let w=b.weather?weatherText(b.weather.code):['⌁','정보 없음'],s=score(b),r=rank(b);return `<button class="card" data-clean="${b.id}"><div class="photo" style="background-image:url('${b.photo}')"><span class="badge">${r===null?'—':r+'위 · '+s+'점'}</span></div><h3>${b.name}</h3><p>청결 정보 보기 · ${w[0]} ${w[1]}</p></button>`}
function render(){let sorted=[...beaches].sort((a,b)=>(score(b)??-1)-(score(a)??-1));$('#cards').innerHTML=sorted.map(card).join('');$('#homeStatus').textContent=`${nowText()} 기준 최신 API 데이터를 반영했어요.`;$('#mapSummary').innerHTML=`<div class="panel"><p class="eyebrow">DATA NOTICE</p><p class="muted">기상·해양 정보는 Open-Meteo API에서 새로 불러옵니다. 혼잡도·주차는 예상 정보이며 수질은 현재 확인되지 않음으로 표시합니다.</p></div>`;renderMap()}
function renderMap(){if(!map){map=L.map('leafletMap',{scrollWheelZoom:true}).setView([35.118,129.075],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map)}map.eachLayer(l=>{if(l instanceof L.Marker)map.removeLayer(l)});beaches.forEach(b=>{let w=b.weather?weatherText(b.weather.code):['⌁','불러올 수 없음'],wave=b.marine?.wave;L.marker([b.lat,b.lon]).addTo(map).bindPopup(`<div class="popup"><h3>${b.name}</h3><p>${w[0]} ${w[1]} · ${b.weather?.temp??'정보 없음'}°C</p><p>풍속 ${b.weather?.wind??'정보 없음'} km/h · 파도 ${wave??'불러올 수 없음'}${wave!==null&&wave!==undefined?'m':''}</p><p>맞춤 점수 <b>${score(b)}점</b></p><button onclick="window.openDetail('${b.id}')">상세 보기</button></div>`)});setTimeout(()=>map.invalidateSize(),50)}
function openDetail(id){current=beaches.find(b=>b.id===id);$('#detailImage').style.backgroundImage=`url('${current.photo}')`;$('#detailName').textContent=current.name;$('#detailScore').textContent=score(current);$('#detailScoreNote').textContent='사용자 가중치와 최신·예상 정보를 함께 계산';$('#updatedAt').textContent='데이터 갱신 시각: '+nowText();let w=current.weather,m=current.marine,wx=w?weatherText(w.code):['⌁','현재 정보를 불러올 수 없습니다'];const facts=[['🌡️','현재 기온',w?`${w.temp}°C`:'현재 정보를 불러올 수 없습니다','실제 API'],['♨️','체감온도',w?`${w.feel}°C`:'현재 정보를 불러올 수 없습니다','실제 API'],[wx[0],'날씨',w?wx[1]:'현재 정보를 불러올 수 없습니다','실제 API'],['〰','파도 높이',m?.wave===null||!m?'해양 데이터를 불러올 수 없습니다':m.wave+'m','실제 API'],['↗','파도 방향',m?.dir===null||!m?'해양 데이터를 불러올 수 없습니다':m.dir+'°','실제 API'],['◌','파도 주기',m?.period===null||!m?'해양 데이터를 불러올 수 없습니다':m.period+'초','실제 API'],['🌊','해수면 온도',m?.sea===null||!m?'해양 데이터를 불러올 수 없습니다':m.sea+'°C','실제 API'],['💨','풍속',w?`${w.wind} km/h`:'현재 정보를 불러올 수 없습니다','실제 API'],['☔','강수 확률',w&&w.prob!==null?`${w.prob}%`:'현재 정보를 불러올 수 없습니다','실제 API'],['◉','혼잡도',congestion(current),'예상 정보'],['▣','주차 여유',parking(current),'예상 정보'],['◇','수질','현재 확인되지 않음','공식 출처 미연결'],['⌂','편의시설',current.facility,'정적 안내']];$('#facts').innerHTML=facts.map(x=>`<div class="fact"><span>${x[0]}</span><p>${x[1]}</p><b>${x[2]}</b><small>${x[3]} · ${nowText()}</small></div>`).join('');$('#basis').innerHTML=[`날씨 적합성: 실제 예보 데이터 (${w?wx[1]:'불러올 수 없음'})`,`파도 적합성: 실제 해양 예보 데이터 (${m?.wave??'불러올 수 없음'}${m?.wave!==null&&m?'m':''})`,`혼잡도: 예상 정보 (${congestion(current)})`,`주차: 예상 정보 (${parking(current)})`,`편의시설: 정적 기본 정보 (${current.facility})`].map(x=>`<li>${x}</li>`).join('');go('detail')}
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav').forEach(n=>n.classList.toggle('on',n.dataset.go===id));if(id==='map')setTimeout(()=>map?.invalidateSize(),100);window.scrollTo(0,0)}
function setup(){const ps=['🏊 물놀이','🚶 산책','🏄 서핑','📷 사진 촬영','👨‍👩‍👧 가족 여행','💙 데이트','🌿 힐링'];$('#purpose').innerHTML=ps.map(x=>`<button class="choice ${x.includes(purpose)?'on':''}" data-purpose="${x.slice(2)}">${x}</button>`).join('');$('#sliders').innerHTML=Object.entries(weights).map(([k,v])=>`<div class="weight"><div><span>${k}</span><b id="w${k}">${v}</b></div><input data-weight="${k}" type="range" min="1" max="5" value="${v}"></div>`).join('');const rail=$('#cards');let drag=false,moved=false,startX=0,startLeft=0,pressedCard=null;rail.style.cursor='grab';rail.style.userSelect='none';rail.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')return;drag=true;moved=false;pressedCard=e.target.closest('[data-clean]');startX=e.clientX;startLeft=rail.scrollLeft;rail.setPointerCapture(e.pointerId);rail.style.cursor='grabbing'});rail.addEventListener('pointermove',e=>{if(!drag)return;let delta=e.clientX-startX;if(Math.abs(delta)>4)moved=true;rail.scrollLeft=startLeft-delta});rail.addEventListener('pointerup',()=>{drag=false;rail.style.cursor='grab';if(!moved&&pressedCard)showClean(pressedCard.dataset.clean);pressedCard=null});rail.addEventListener('pointercancel',()=>{drag=false;pressedCard=null;rail.style.cursor='grab'});rail.addEventListener('click',e=>{if(moved){e.preventDefault();e.stopPropagation();moved=false}},true)}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function loadNearbyPlaces(){const attractions={haeundae:[['더베이101','마린시티 야경과 요트 풍경을 즐기기 좋은 명소'],['동백섬','해안 산책로와 누리마루 APEC 하우스가 있는 섬'],['청사포 다릿돌전망대','바다 위를 걷는 듯한 유리 바닥 전망대']],gwangalli:[['광안대교','광안리 해변에서 만나는 부산 대표 야경'],['민락수변공원','바다를 바라보며 쉬기 좋은 수변 공원'],['F1963','옛 철강공장을 문화공간으로 바꾼 복합 문화 명소']],songjeong:[['해동용궁사','바닷가 절벽 위에 자리한 사찰'],['청사포 다릿돌전망대','해안 풍경을 가까이 감상하는 전망대'],['미포철길','동해남부선 옛 철길을 따라 걷는 산책 명소']],songdo:[['송도해상케이블카','송도 바다를 가로지르는 케이블카'],['송도용궁구름다리','암남공원과 이어지는 해상 보행교'],['암남공원','해안 절벽과 숲길을 함께 즐기는 공원']],dadaepo:[['다대포 꿈의 낙조분수','음악과 빛을 함께 즐기는 분수 광장'],['다대포 해변공원','넓은 모래사장과 낙조가 아름다운 공원'],['아미산 전망대','낙동강 하구와 다대포 바다를 조망하는 전망대']]};const out=$('#foodTypes'),items=attractions[current.id]||[];out.innerHTML=items.map((x,i)=>`<article class="food"><b>${i+1}. ${x[0]}</b><p>${x[1]} · 정적 관광 안내</p></article>`).join('')}
document.addEventListener('click',e=>{let g=e.target.closest('[data-go]');if(g)go(g.dataset.go);if(e.target.closest('.close-page,.back'))go('home');let d=e.target.closest('[data-detail]');if(d)openDetail(d.dataset.detail);let p=e.target.closest('[data-purpose]');if(p){purpose=p.dataset.purpose;$$('.choice').forEach(x=>x.classList.toggle('on',x===p))}});document.addEventListener('input',e=>{if(e.target.dataset.weight){weights[e.target.dataset.weight]=+e.target.value;$('#w'+e.target.dataset.weight).textContent=e.target.value}});$('#recommendBtn').onclick=()=>{if(!loaded)return toast('실제 데이터를 불러오는 중이에요. 잠시 후 다시 시도해 주세요.');let candidates=beaches.filter(b=>score(b)!==null);if(!candidates.length)return toast('필수 실제 데이터를 불러올 수 없어 추천 점수를 계산할 수 없습니다.');let b=candidates.sort((a,b)=>score(b)-score(a))[0];openDetail(b.id);toast(`${b.name}을(를) 추천해요.`)};$('#foodBtn').onclick=()=>{ $('#foodArea').textContent='NEAR '+current.name;go('food');loadNearbyPlaces()};$('#searchFood').onclick=()=>window.open(`https://map.kakao.com/?q=${encodeURIComponent(current.name+' '+current.food)}`,'_blank','noopener');window.openDetail=openDetail;
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();let css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);let s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=()=>reject(new Error('Leaflet CDN load failed'));document.head.appendChild(s)})}
async function init(){setup();document.querySelector('#home .heading h2').textContent='해변 청결 정보';try{await loadLeaflet();await Promise.all(beaches.map(fetchBeach));loaded=true;render();toast('실제 기상·해양 데이터를 불러왔어요.')}catch(e){console.error('[PadoPick init]',e);$('#homeStatus').textContent='일부 실제 정보를 불러올 수 없습니다.';$('#cards').innerHTML='<div class="loading">현재 정보를 불러올 수 없습니다. 잠시 후 새로고침해 주세요.</div>'} }init();
const officialQuality={haeundae:{score:5,cod:'0.3',coli:14},gwangalli:{score:8,cod:'1.0',coli:113},songjeong:{score:5,cod:'0.3',coli:203},songdo:{score:5,cod:'0.9',coli:428},dadaepo:{score:7,cod:'1.6',coli:120}};
const baseOpenDetail=openDetail;openDetail=function(id){baseOpenDetail(id);const q=officialQuality[id],fact=[...document.querySelectorAll('#facts .fact')].find(x=>x.querySelector('p')?.textContent==='수질');if(fact&&q)fact.innerHTML=`<span>◇</span><p>수질</p><b>적합 · 총점 ${q.score}점</b><small>부산광역시 공식 자료 · COD ${q.cod} mg/L</small>`;};
